apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opa.fullname" . }}-config
  labels:
    app: {{ template "opa.fullname" . }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.opa | b64enc }}
