kind: Service
apiVersion: v1
metadata:
  name: {{ template "opa.fullname" . }}
spec:
  selector:
    app: {{ template "opa.fullname" . }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
